(add-to-list 'load-path "~/.emacs.d/my-emacs/haskell/")
(load "~/.emacs.d/my-emacs/haskell/haskell-mode/haskell-site-file.el")
(add-hook 'haskell-mode-hook 'turn-on-font-lock)
(add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
(require 'hs-lint)
(defun my-haskell-mode-hook ()
  (local-set-key "\C-cl" 'hs-lint))
(add-hook 'haskell-mode-hook 'my-haskell-mode-hook)
